language: python
python: 3.5
env:
  matrix:
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=py36
cache:
  directories:
    - $HOME/.cache/pip
install: pip install docutils tox
script: tox
